### ISSUE TITLE
Multiplayer Rimworld compatibility

### ISSUE THREAD

**Issue by gitignore-dumbcow** [pardeike/NoPauseChallenge#4]

**Comment by pardeike** [comment]
What about it?

**Comment by gitignore-dumbcow** [comment]
So I tried using the mod with the Multiplayer Rimworld mod, and everything worked just fine on the host, but other clients seem to lag behind by a lot and time just stayed there, nothing happened. After that, I checked the compatibility of the Multiplayer Rimworld mod and it shows this "image". I'm asking if No pause will implement fixing this problem or if I can just use it in singleplayer.

![image](https://user-images.githubusercontent.com/61190119/184156929-fd227b1c-4e40-4e96-b611-357c18cfc13a.png)
